/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto3;

/**
 *
 * @author Marco
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregarEvento = new javax.swing.JButton();
        jButtonModificarEvento = new javax.swing.JButton();
        jButtonConsultarEvento = new javax.swing.JButton();
        jButtonAgendaEventos = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setLocation(new java.awt.Point(200, 200));
        setResizable(false);

        jButtonAgregarEvento.setText("Agregar evento");
        jButtonAgregarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEventoActionPerformed(evt);
            }
        });

        jButtonModificarEvento.setText("Modificar evento");
        jButtonModificarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEventoActionPerformed(evt);
            }
        });

        jButtonConsultarEvento.setText("Consultar evento");
        jButtonConsultarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarEventoActionPerformed(evt);
            }
        });

        jButtonAgendaEventos.setText("Agenda de eventos");
        jButtonAgendaEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaEventosActionPerformed(evt);
            }
        });

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto3/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregarEvento)
                    .addComponent(jButtonModificarEvento)
                    .addComponent(jButtonConsultarEvento)
                    .addComponent(jButtonAgendaEventos))
                .addGap(18, 18, 18)
                .addComponent(jLabelLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAgregarEvento)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificarEvento)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConsultarEvento)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAgendaEventos))
                    .addComponent(jLabelLogo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEventoActionPerformed
        // TODO add your handling code here:
        Agregar ventanaAgregar = new Agregar();
        ventanaAgregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAgregarEventoActionPerformed

    private void jButtonConsultarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEventoActionPerformed
        // TODO add your handling code here:
        Consultar ventanaConsultar = new Consultar();
        ventanaConsultar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonConsultarEventoActionPerformed

    private void jButtonAgendaEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaEventosActionPerformed
        // TODO add your handling code here:
        Agenda ventanaAgenda = new Agenda();
        ventanaAgenda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAgendaEventosActionPerformed

    private void jButtonModificarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEventoActionPerformed
        // TODO add your handling code here:
        Modify windowModify = new Modify();
        windowModify.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonModificarEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendaEventos;
    private javax.swing.JButton jButtonAgregarEvento;
    private javax.swing.JButton jButtonConsultarEvento;
    private javax.swing.JButton jButtonModificarEvento;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
